<?php
?>

<footer class="site-footer">
    <div class="container footer-layout">
        <div>
            <p>&copy; 2026 ShopSphere</p>
            <p><a href="mailto:info@shopsphere.com">info@shopsphere.com</a></p>
        </div>
        <div class="footer-links">
            <p><a href="https://2568879251l.atlassian.net/jira/software/projects/SCRUM/boards/1">Jira Project Link</a></p>
            <p><a href="https://github.com/105965256/COS10026-Group-Work">GitHub Repository Link</a></p>
            <p><a href="https://105965256.github.io/COS10026-Group-Work/">GitHub Pages</a></p>
        </div>
    </div>
</footer>

</body>
</html>